title: Oluwafemi Data Analytics Potfolio
logo: /assets/img/logo.png
description: With about a decade of experience in data analysis, I excel in working with diverse data sources and transforming complex datasets into actionable insights that support informed decision-making.My extensive experience in data analysis is complemented by a solid educational background. I am adept with statistical and data analytics tools such as E-Views, Excel, SQL, and Power BI. As a dedicated and detail-oriented analyst, I am ready to contribute to the success of dynamic organizations in this multifaceted role
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
