title: Oluwafemi Data Analytics Potfolio
logo: /assets/img/logo.png
description: A data Analyst with 2years experience working across different sectors, highly skilled in SQL, PowerBi, and Excel
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
